version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
     - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
  api:
    container_name: API-INTERLUP-DSF
    env_file:
      - .env
    build: .
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    restart: always

volumes:
  pgdata:
